package com.google.android.gms.measurement.internal;

import android.content.Context;
import androidx.recyclerview.widget.m;
import java.util.ArrayList;
import java.util.Collections;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

@com.google.android.gms.common.util.d0
/* loaded from: classes.dex */
public final class u {
    public static l3<Boolean> A0;
    public static l3<Boolean> B0;
    public static l3<Boolean> C0;
    public static l3<Boolean> D0;
    public static l3<Boolean> E0;
    public static l3<Boolean> F0;
    public static l3<Integer> G;
    public static l3<Long> G0;
    public static l3<Integer> H;
    public static l3<Boolean> H0;
    public static l3<Integer> I;
    public static l3<Boolean> I0;
    public static l3<Integer> J;
    public static l3<Boolean> J0;
    public static l3<Long> K;
    public static l3<Boolean> K0;
    public static l3<Boolean> L;
    public static l3<Boolean> L0;
    public static l3<String> M;
    public static l3<Integer> M0;
    public static l3<Long> N;
    public static l3<Boolean> N0;
    public static l3<Integer> O;
    public static l3<Boolean> O0;
    public static l3<Double> P;
    public static l3<Boolean> P0;
    public static l3<Integer> Q;
    public static l3<Boolean> Q0;
    public static l3<Integer> R;
    public static l3<Boolean> S;
    public static l3<Boolean> T;
    public static l3<Boolean> U;
    public static l3<Boolean> V;
    public static l3<Boolean> W;
    public static l3<Boolean> X;
    public static l3<Boolean> Y;
    public static l3<Boolean> Z;
    public static l3<Boolean> a0;
    public static l3<Boolean> b0;
    public static l3<Boolean> c0;
    public static l3<Boolean> d0;
    public static l3<Boolean> e0;
    public static l3<Boolean> f0;
    public static l3<Boolean> g0;
    public static l3<Boolean> h0;
    public static l3<Boolean> i0;
    public static l3<Boolean> j0;
    public static l3<Boolean> k0;
    public static l3<Boolean> l0;
    public static l3<Boolean> m0;
    public static l3<Boolean> n0;
    public static l3<Boolean> o0;
    public static l3<Boolean> p0;
    public static l3<Boolean> q0;
    public static l3<Boolean> r0;
    public static l3<Boolean> s0;
    public static l3<Boolean> t0;
    public static l3<Boolean> u0;
    public static l3<Boolean> v0;
    public static l3<Boolean> w0;
    private static l3<Boolean> x0;
    public static l3<Boolean> y0;
    public static l3<Boolean> z0;

    /* renamed from: a, reason: collision with root package name */
    private static List<l3<?>> f6525a = Collections.synchronizedList(new ArrayList());

    /* renamed from: b, reason: collision with root package name */
    private static Set<l3<?>> f6526b = Collections.synchronizedSet(new HashSet());

    /* renamed from: c, reason: collision with root package name */
    public static l3<Long> f6527c = a("measurement.ad_id_cache_time", 10000L, 10000L, t.f6514a);
    public static l3<Long> d = a("measurement.monitoring.sample_period_millis", 86400000L, 86400000L, w.f6546a);
    public static l3<Long> e = a("measurement.config.cache_time", 86400000L, 3600000L, g0.f6392a);
    public static l3<String> f = a("measurement.config.url_scheme", "https", "https", t0.f6515a);
    public static l3<String> g = a("measurement.config.url_authority", "app-measurement.com", "app-measurement.com", d1.f6369a);
    public static l3<Integer> h = a("measurement.upload.max_bundles", 100, 100, q1.f6493a);
    public static l3<Integer> i = a("measurement.upload.max_batch_size", 65536, 65536, z1.f6575a);
    public static l3<Integer> j = a("measurement.upload.max_bundle_size", 65536, 65536, n2.f6466a);
    public static l3<Integer> k = a("measurement.upload.max_events_per_bundle", 1000, 1000, w2.f6549a);
    public static l3<Integer> l = a("measurement.upload.max_events_per_day", 100000, 100000, h3.f6403a);
    public static l3<Integer> m = a("measurement.upload.max_error_events_per_day", 1000, 1000, v.f6539a);
    public static l3<Integer> n = a("measurement.upload.max_public_events_per_day", 50000, 50000, y.f6564a);
    public static l3<Integer> o = a("measurement.upload.max_conversions_per_day", 10000, 10000, x.f6554a);
    public static l3<Integer> p = a("measurement.upload.max_realtime_events_per_day", 10, 10, a0.f6342a);
    public static l3<Integer> q = a("measurement.store.max_stored_events_per_app", 100000, 100000, z.f6573a);
    public static l3<String> r = a("measurement.upload.url", "https://app-measurement.com/a", "https://app-measurement.com/a", d0.f6368a);
    public static l3<Long> s = a("measurement.upload.backoff_period", 43200000L, 43200000L, c0.f6362a);
    public static l3<Long> t = a("measurement.upload.window_interval", 3600000L, 3600000L, f0.f6381a);
    public static l3<Long> u = a("measurement.upload.interval", 3600000L, 3600000L, e0.f6374a);
    public static l3<Long> v = a("measurement.upload.realtime_upload_interval", 10000L, 10000L, h0.f6400a);
    public static l3<Long> w = a("measurement.upload.debug_upload_interval", 1000L, 1000L, j0.f6412a);
    public static l3<Long> x = a("measurement.upload.minimum_delay", 500L, 500L, i0.f6408a);
    public static l3<Long> y = a("measurement.alarm_manager.minimum_interval", 60000L, 60000L, l0.f6438a);
    public static l3<Long> z = a("measurement.upload.stale_data_deletion_interval", 86400000L, 86400000L, k0.f6426a);
    public static l3<Long> A = a("measurement.upload.refresh_blacklisted_config_interval", 604800000L, 604800000L, n0.f6464a);
    public static l3<Long> B = a("measurement.upload.initial_upload_delay_time", 15000L, 15000L, m0.f6454a);
    public static l3<Long> C = a("measurement.upload.retry_time", 1800000L, 1800000L, p0.f6479a);
    public static l3<Integer> D = a("measurement.upload.retry_count", 6, 6, o0.f6474a);
    public static l3<Long> E = a("measurement.upload.max_queue_time", 2419200000L, 2419200000L, r0.f6499a);
    public static l3<Integer> F = a("measurement.lifetimevalue.max_currency_tracked", 4, 4, q0.f6492a);

    static {
        Integer numValueOf = Integer.valueOf(m.f.f719b);
        G = a("measurement.audience.filter_result_max_count", numValueOf, numValueOf, s0.f6503a);
        H = a("measurement.upload.max_public_user_properties", 25, 25, null);
        I = a("measurement.upload.max_event_name_cardinality", 500, 500, null);
        J = a("measurement.upload.max_public_event_params", 25, 25, null);
        K = a("measurement.service_client.idle_disconnect_millis", 5000L, 5000L, v0.f6540a);
        Boolean bool = Boolean.FALSE;
        L = a("measurement.test.boolean_flag", bool, bool, u0.f6528a);
        M = a("measurement.test.string_flag", "---", "---", x0.f6555a);
        N = a("measurement.test.long_flag", -1L, -1L, w0.f6547a);
        O = a("measurement.test.int_flag", -2, -2, z0.f6574a);
        Double dValueOf = Double.valueOf(-3.0d);
        P = a("measurement.test.double_flag", dValueOf, dValueOf, y0.f6565a);
        Q = a("measurement.experiment.max_ids", 50, 50, b1.f6351a);
        R = a("measurement.max_bundles_per_iteration", 100, 100, a1.f6343a);
        Boolean bool2 = Boolean.FALSE;
        S = a("measurement.validation.internal_limits_internal_event_params", bool2, bool2, e1.f6375a);
        Boolean bool3 = Boolean.TRUE;
        T = a("measurement.collection.firebase_global_collection_flag_enabled", bool3, bool3, g1.f6393a);
        Boolean bool4 = Boolean.TRUE;
        U = a("measurement.collection.efficient_engagement_reporting_enabled_2", bool4, bool4, f1.f6382a);
        Boolean bool5 = Boolean.FALSE;
        V = a("measurement.collection.redundant_engagement_removal_enabled", bool5, bool5, i1.f6409a);
        Boolean bool6 = Boolean.TRUE;
        W = a("measurement.client.freeride_engagement_fix", bool6, bool6, h1.f6401a);
        Boolean bool7 = Boolean.TRUE;
        X = a("measurement.collection.log_event_and_bundle_v2", bool7, bool7, k1.f6427a);
        Boolean bool8 = Boolean.FALSE;
        Y = a("measurement.quality.checksum", bool8, bool8, null);
        Boolean bool9 = Boolean.FALSE;
        Z = a("measurement.sdk.dynamite.allow_remote_dynamite3", bool9, bool9, j1.f6413a);
        Boolean bool10 = Boolean.TRUE;
        a0 = a("measurement.sdk.collection.validate_param_names_alphabetical", bool10, bool10, m1.f6455a);
        Boolean bool11 = Boolean.FALSE;
        b0 = a("measurement.audience.use_bundle_end_timestamp_for_non_sequence_property_filters", bool11, bool11, l1.f6439a);
        Boolean bool12 = Boolean.FALSE;
        c0 = a("measurement.audience.refresh_event_count_filters_timestamp", bool12, bool12, o1.f6475a);
        Boolean bool13 = Boolean.FALSE;
        d0 = a("measurement.audience.use_bundle_timestamp_for_event_count_filters", bool13, bool13, n1.f6465a);
        Boolean bool14 = Boolean.TRUE;
        e0 = a("measurement.sdk.collection.retrieve_deeplink_from_bow_2", bool14, bool14, p1.f6480a);
        Boolean bool15 = Boolean.TRUE;
        f0 = a("measurement.sdk.collection.last_deep_link_referrer2", bool15, bool15, s1.f6504a);
        Boolean bool16 = Boolean.FALSE;
        g0 = a("measurement.sdk.collection.last_deep_link_referrer_campaign2", bool16, bool16, r1.f6500a);
        Boolean bool17 = Boolean.FALSE;
        h0 = a("measurement.sdk.collection.last_gclid_from_referrer2", bool17, bool17, u1.f6529a);
        Boolean bool18 = Boolean.TRUE;
        i0 = a("measurement.sdk.collection.enable_extend_user_property_size", bool18, bool18, t1.f6516a);
        Boolean bool19 = Boolean.FALSE;
        j0 = a("measurement.upload.file_lock_state_check", bool19, bool19, w1.f6548a);
        Boolean bool20 = Boolean.FALSE;
        k0 = a("measurement.ga.ga_app_id", bool20, bool20, v1.f6541a);
        Boolean bool21 = Boolean.FALSE;
        l0 = a("measurement.lifecycle.app_in_background_parameter", bool21, bool21, y1.f6566a);
        Boolean bool22 = Boolean.FALSE;
        m0 = a("measurement.integration.disable_firebase_instance_id", bool22, bool22, x1.f6556a);
        Boolean bool23 = Boolean.FALSE;
        n0 = a("measurement.lifecycle.app_backgrounded_engagement", bool23, bool23, a2.f6344a);
        Boolean bool24 = Boolean.FALSE;
        o0 = a("measurement.collection.service.update_with_analytics_fix", bool24, bool24, c2.f6363a);
        Boolean bool25 = Boolean.FALSE;
        p0 = a("measurement.service.use_appinfo_modified", bool25, bool25, b2.f6352a);
        Boolean bool26 = Boolean.TRUE;
        q0 = a("measurement.client.firebase_feature_rollout.v1.enable", bool26, bool26, f2.f6383a);
        Boolean bool27 = Boolean.TRUE;
        r0 = a("measurement.client.sessions.check_on_reset_and_enable2", bool27, bool27, e2.f6376a);
        Boolean bool28 = Boolean.FALSE;
        s0 = a("measurement.scheduler.task_thread.cleanup_on_exit", bool28, bool28, h2.f6402a);
        Boolean bool29 = Boolean.FALSE;
        t0 = a("measurement.upload.file_truncate_fix", bool29, bool29, g2.f6394a);
        Boolean bool30 = Boolean.FALSE;
        u0 = a("measurement.sdk.referrer.delayed_install_referrer_api", bool30, bool30, j2.f6414a);
        Boolean bool31 = Boolean.TRUE;
        v0 = a("measurement.sdk.screen.disabling_automatic_reporting", bool31, bool31, i2.f6410a);
        Boolean bool32 = Boolean.TRUE;
        w0 = a("measurement.sdk.screen.manual_screen_view_logging", bool32, bool32, l2.f6440a);
        Boolean bool33 = Boolean.FALSE;
        x0 = a("measurement.collection.synthetic_data_mitigation", bool33, bool33, k2.f6428a);
        Boolean bool34 = Boolean.TRUE;
        y0 = a("measurement.service.configurable_service_limits", bool34, bool34, m2.f6456a);
        Boolean bool35 = Boolean.TRUE;
        z0 = a("measurement.client.configurable_service_limits", bool35, bool35, p2.f6481a);
        Boolean bool36 = Boolean.TRUE;
        A0 = a("measurement.androidId.delete_feature", bool36, bool36, o2.f6476a);
        Boolean bool37 = Boolean.TRUE;
        B0 = a("measurement.client.global_params", bool37, bool37, r2.f6501a);
        Boolean bool38 = Boolean.TRUE;
        C0 = a("measurement.service.global_params", bool38, bool38, q2.f6494a);
        Boolean bool39 = Boolean.TRUE;
        D0 = a("measurement.service.global_params_in_payload", bool39, bool39, t2.f6517a);
        Boolean bool40 = Boolean.TRUE;
        E0 = a("measurement.client.string_reader", bool40, bool40, s2.f6505a);
        Boolean bool41 = Boolean.TRUE;
        F0 = a("measurement.sdk.attribution.cache", bool41, bool41, v2.f6542a);
        G0 = a("measurement.sdk.attribution.cache.ttl", 604800000L, 604800000L, u2.f6530a);
        Boolean bool42 = Boolean.TRUE;
        H0 = a("measurement.service.database_return_empty_collection", bool42, bool42, x2.f6557a);
        Boolean bool43 = Boolean.TRUE;
        I0 = a("measurement.service.ssaid_removal", bool43, bool43, z2.f6576a);
        Boolean bool44 = Boolean.TRUE;
        J0 = a("measurement.client.consent_state_v1", bool44, bool44, y2.f6567a);
        Boolean bool45 = Boolean.FALSE;
        K0 = a("measurement.client.3p_consent_state_v1.dev", bool45, bool45, b3.f6353a);
        Boolean bool46 = Boolean.FALSE;
        L0 = a("measurement.service.consent_state_v1_W36", bool46, bool46, a3.f6345a);
        M0 = a("measurement.service.storage_consent_support_version", 203590, 203590, d3.f6370a);
        Boolean bool47 = Boolean.TRUE;
        N0 = a("measurement.client.ad_impression", bool47, bool47, c3.f6364a);
        Boolean bool48 = Boolean.TRUE;
        O0 = a("measurement.service.ad_impression", bool48, bool48, g3.f6395a);
        Boolean bool49 = Boolean.TRUE;
        P0 = a("measurement.service.separate_public_internal_event_blacklisting", bool49, bool49, f3.f6384a);
        Boolean bool50 = Boolean.FALSE;
        Q0 = a("measurement.service.directly_maybe_log_error_events", bool50, bool50, i3.f6411a);
    }

    @com.google.android.gms.common.util.d0
    private static <V> l3<V> a(@androidx.annotation.i0 String str, @androidx.annotation.i0 V v2, @androidx.annotation.i0 V v3, @androidx.annotation.i0 j3<V> j3Var) {
        l3<V> l3Var = new l3<>(str, v2, v3, j3Var);
        f6525a.add(l3Var);
        return l3Var;
    }

    public static Map<String, String> c(Context context) {
        c.a.b.b.g.c.w1 w1VarA = c.a.b.b.g.c.w1.a(context.getContentResolver(), c.a.b.b.g.c.i2.a("com.google.android.gms.measurement"));
        return w1VarA == null ? Collections.emptyMap() : w1VarA.b();
    }
}
