package com.google.android.gms.internal.ads;

import android.content.Context;
import android.content.SharedPreferences;
import androidx.appcompat.widget.ActivityChooserView;
import androidx.recyclerview.widget.m;
import java.util.List;
import java.util.concurrent.TimeUnit;
import org.json.JSONObject;

/* loaded from: classes.dex */
public final class e0 {
    public static final s<Boolean> A2;
    private static final s<Boolean> A3;
    public static final s<Integer> A4;
    public static final s<Long> B2;
    private static final s<String> B3;
    public static final s<String> B4;
    public static final s<Long> C2;
    public static final s<Boolean> C3;
    public static final s<String> C4;
    private static final s<Integer> D2;
    public static final s<Boolean> D3;
    public static final s<String> D4;
    private static final s<Integer> E2;
    private static final s<Boolean> E3;
    public static final s<String> E4;
    private static final s<Long> F2;
    public static final s<Boolean> F3;
    public static final s<Integer> F4;
    public static final s<Boolean> G2;
    public static final s<Boolean> G3;
    public static final s<Integer> G4;
    public static final s<Boolean> H2;
    private static final s<Boolean> H3;
    public static final s<Integer> H4;
    public static final s<Boolean> I2;
    public static final s<Boolean> I3;
    public static final s<Integer> I4;
    public static final s<Long> J2;
    public static final s<Integer> J3;
    public static final s<String> J4;
    public static final s<Boolean> K2;
    public static final s<Boolean> K3;
    public static final s<String> K4;
    public static final s<Boolean> L2;
    public static final s<Boolean> L3;
    public static final s<String> L4;
    public static final s<Long> M2;
    public static final s<Boolean> M3;
    public static final s<String> M4;
    public static final s<Long> N2;
    public static final s<Boolean> N3;
    public static final s<Integer> N4;
    public static final s<Boolean> O2;
    public static final s<Boolean> O3;
    public static final s<String> O4;
    public static final s<String> P2;
    public static final s<Boolean> P3;
    public static final s<Integer> P4;
    public static final s<Integer> Q2;
    private static final s<Boolean> Q3;
    public static final s<Integer> Q4;
    public static final s<Boolean> R2;
    public static final s<Boolean> R3;
    public static final s<Boolean> R4;
    public static final s<Boolean> S2;
    public static final s<Boolean> S3;
    public static final s<Boolean> S4;
    public static final s<Long> T2;
    public static final s<Boolean> T3;
    public static final s<Boolean> T4;
    public static final s<String> U2;
    public static final s<Boolean> U3;
    public static final s<Boolean> U4;
    public static final s<String> V2;
    public static final s<Boolean> V3;
    public static final s<Boolean> V4;
    public static final s<String> W2;
    private static final s<Boolean> W3;
    public static final s<String> W4;
    public static final s<String> X2;
    public static final s<Boolean> X3;
    public static final s<Boolean> X4;
    public static final s<Integer> Y2;
    private static final s<Boolean> Y3;
    public static final s<Integer> Y4;
    private static final s<String> Z1;
    public static final s<Integer> Z2;
    public static final s<Boolean> Z3;
    public static final s<Integer> Z4;
    public static final s<String> a2;
    public static final s<Boolean> a3;
    private static final s<Boolean> a4;
    public static final s<Boolean> a5;
    private static final s<Boolean> b2;
    public static final s<Boolean> b3;
    public static final s<Boolean> b4;
    public static final s<Boolean> b5;
    public static final s<String> c2;
    public static final s<Boolean> c3;
    public static final s<Boolean> c4;
    public static final s<Boolean> c5;
    private static final s<String> d2;
    public static final s<Integer> d3;
    public static final s<Boolean> d4;
    public static final s<Boolean> d5;
    public static final s<String> e2;
    public static final s<Boolean> e3;
    private static final s<Boolean> e4;
    public static final s<Boolean> e5;
    public static final s<Boolean> f2;
    public static final s<Boolean> f3;
    public static final s<Long> f4;
    public static final s<Boolean> f5;
    public static final s<Integer> g2;
    public static final s<Boolean> g3;
    public static final s<Integer> g4;
    public static final s<Integer> g5;
    private static final s<Integer> h2;
    public static final s<String> h3;
    public static final s<Integer> h4;
    public static final s<Boolean> h5;
    public static final s<Boolean> i2;
    public static final s<String> i3;
    public static final s<Integer> i4;
    public static final s<Integer> i5;
    public static final s<Boolean> j2;
    public static final s<Integer> j3;
    public static final s<Integer> j4;
    public static final s<Integer> j5;
    public static final s<Boolean> k2;
    public static final s<Boolean> k3;
    private static final m1<Boolean> k4;
    public static final s<Boolean> k5;
    public static final s<String> l2;
    public static final s<Integer> l3;
    public static final s<Boolean> l4;
    public static final s<Boolean> l5;
    private static final s<Boolean> m2;
    private static final s<Boolean> m3;
    public static final s<Boolean> m4;
    public static final s<Boolean> m5;
    public static final s<Boolean> n2;
    private static final s<Boolean> n3;
    public static final s<Boolean> n4;
    public static final s<Boolean> n5;
    public static final s<Boolean> o2;
    private static final s<Boolean> o3;
    public static final s<String> o4;
    public static final s<Boolean> o5;
    public static final s<Boolean> p2;
    private static final s<Boolean> p3;
    public static final s<Boolean> p4;
    public static final s<Boolean> p5;
    private static final s<Boolean> q2;
    private static final s<String> q3;
    public static final s<Integer> q4;
    public static final s<Boolean> q5;
    public static final s<Boolean> r2;
    private static final s<Boolean> r3;
    public static final s<Boolean> r4;
    public static final s<Boolean> r5;
    private static final s<Boolean> s2;
    public static final s<Integer> s3;
    public static final s<Boolean> s4;
    public static final s<String> s5;
    private static final s<String> t2;
    public static final s<Integer> t3;
    public static final s<Integer> t4;
    public static final s<Boolean> t5;
    public static final s<Long> u2;
    private static final s<String> u3;
    public static final s<Boolean> u4;
    public static final s<Boolean> u5;
    private static final s<String> v2;
    private static final s<Boolean> v3;
    public static final s<Boolean> v4;
    public static final s<Integer> v5;
    private static final s<Long> w2;
    private static final s<String> w3;
    public static final s<Boolean> w4;
    public static final s<Boolean> w5;
    private static final s<String> x2;
    private static final s<Boolean> x3;
    public static final s<Boolean> x4;
    public static final s<Boolean> x5;
    public static final s<Boolean> y2;
    public static final s<Boolean> y3;
    public static final s<Boolean> y4;
    public static final s<Integer> y5;
    public static final s<Boolean> z2;
    public static final s<String> z3;
    public static final s<Integer> z4;
    public static final s<Boolean> z5;

    /* renamed from: a, reason: collision with root package name */
    public static final s<String> f3190a = s.f(1, "gads:sdk_core_location:client:html", "https://googleads.g.doubleclick.net/mads/static/mad/sdk/native/production/sdk-core-v40-impl.html");

    /* renamed from: b, reason: collision with root package name */
    public static final s<String> f3191b = s.f(1, "gads:active_view_location:html", "https://googleads.g.doubleclick.net/mads/static/mad/sdk/native/production/sdk-core-v40-impl.html");

    /* renamed from: c, reason: collision with root package name */
    private static final m1<Boolean> f3192c = b2.d;
    private static final s<Integer> d = s.d(1, "gads:http_url_connection_factory:timeout_millis", 10000);
    public static final s<String> e = s.f(1, "gads:video_exo_player:version", "3");
    public static final s<Integer> f = s.d(1, "gads:video_exo_player:connect_timeout", 8000);
    public static final s<Integer> g = s.d(1, "gads:video_exo_player:read_timeout", 8000);
    public static final s<Integer> h = s.d(1, "gads:video_exo_player:loading_check_interval", 1048576);
    public static final s<Integer> i = s.d(1, "gads:video_exo_player:exo_player_precache_limit", ActivityChooserView.f.j);
    public static final s<Integer> j = s.d(1, "gads:video_exo_player:byte_buffer_precache_limit", ActivityChooserView.f.j);
    public static final s<Integer> k = s.d(1, "gads:video_exo_player_socket_receive_buffer_size", 0);
    public static final s<String> l = s.f(1, "gads:video_exo_player:precache_exceptions", "");
    public static final s<Integer> m = s.d(1, "gads:video_exo_player:min_retry_count", -1);
    public static final s<Boolean> n = s.e(1, "gads:video_exo_player:fmp4_extractor_enabled", Boolean.FALSE);
    public static final s<Integer> o = s.d(1, "gads:video_stream_cache:limit_count", 5);
    public static final s<Integer> p = s.d(1, "gads:video_stream_cache:limit_space", 8388608);
    public static final s<Integer> q = s.d(1, "gads:video_stream_exo_cache:buffer_size", 8388608);
    public static final s<Long> r = s.k(1, "gads:video_stream_cache:limit_time_sec", 300);
    public static final s<Long> s = s.k(1, "gads:video_stream_cache:notify_interval_millis", 125);
    public static final s<Integer> t = s.d(1, "gads:video_stream_cache:connect_timeout_millis", 10000);
    public static final s<String> u = s.f(1, "gads:video:metric_frame_hash_times", "");
    public static final s<Long> v = s.k(1, "gads:video:metric_frame_hash_time_leniency", 500);
    public static final s<Boolean> w = s.e(1, "gads:video:force_watermark", Boolean.FALSE);
    public static final s<Long> x = s.k(1, "gads:video:surface_update_min_spacing_ms", 1000);
    public static final s<Boolean> y = s.e(1, "gads:video:spinner:enabled", Boolean.FALSE);
    public static final s<Integer> z = s.d(1, "gads:video:spinner:scale", 4);
    public static final s<Long> A = s.k(1, "gads:video:spinner:jank_threshold_ms", 50);
    public static final s<Boolean> B = s.e(1, "gads:video:aggressive_media_codec_release", Boolean.FALSE);
    public static final s<Boolean> C = s.e(1, "gads:memory_bundle:debug_info", Boolean.FALSE);
    public static final s<String> D = s.f(1, "gads:video:codec_query_mime_types", "");
    public static final s<Integer> E = s.d(1, "gads:video:codec_query_minimum_version", 16);
    public static final s<String> F = s.f(1, "gad:mraid:url_banner", "https://googleads.g.doubleclick.net/mads/static/mad/sdk/native/production/mraid/v3/mraid_app_banner.js");
    public static final s<String> G = s.f(1, "gad:mraid:url_expanded_banner", "https://googleads.g.doubleclick.net/mads/static/mad/sdk/native/production/mraid/v3/mraid_app_expanded_banner.js");
    public static final s<String> H = s.f(1, "gad:mraid:url_interstitial", "https://googleads.g.doubleclick.net/mads/static/mad/sdk/native/production/mraid/v3/mraid_app_interstitial.js");
    public static final s<String> I = s.f(1, "gad:mraid:version", "3.0");
    public static final s<Boolean> J = s.e(1, "gads:mraid:expanded_interstitial_fix", Boolean.FALSE);
    public static final s<Boolean> K = s.e(1, "gads:mraid:initial_size_fallback", Boolean.FALSE);
    public static final s<Integer> L = s.d(1, "gads:content_vertical_fingerprint_number", 100);
    public static final s<Integer> M = s.d(1, "gads:content_vertical_fingerprint_bits", 23);
    public static final s<Integer> N = s.d(1, "gads:content_vertical_fingerprint_ngram", 3);
    public static final s<String> O = s.f(1, "gads:content_fetch_view_tag_id", "googlebot");
    public static final s<String> P = s.f(1, "gads:content_fetch_exclude_view_tag", "none");
    public static final s<Boolean> Q = s.e(1, "gads:content_fetch_disable_get_title_from_webview", Boolean.FALSE);
    public static final s<Boolean> R = s.e(1, "gads:content_fetch_enable_new_content_score", Boolean.FALSE);
    public static final s<Boolean> S = s.e(1, "gads:content_fetch_enable_serve_once", Boolean.FALSE);
    public static final s<Boolean> T = s.e(1, "gads:sai:enabled", Boolean.TRUE);
    public static final s<String> U = s.f(1, "gads:sai:click_ping_schema_v2", "^[^?]*(/aclk\\?|/pcs/click\\?).*");
    public static final s<String> V = s.f(1, "gads:sai:impression_ping_schema_v2", "^[^?]*(/adview|/pcs/view).*");
    public static final s<Boolean> W = s.e(1, "gads:sai:using_macro:enabled", Boolean.FALSE);
    public static final s<String> X = s.f(1, "gads:sai:ad_event_id_macro_name", "[gw_fbsaeid]");
    public static final s<Long> Y = s.k(1, "gads:sai:timeout_ms", -1);
    public static final s<Integer> Z = s.d(1, "gads:sai:scion_thread_pool_size", 5);
    public static final s<Boolean> a0 = s.e(1, "gads:sai:app_measurement_enabled3", Boolean.FALSE);
    public static final s<Integer> b0 = s.d(1, "gads:sai:app_measurement_min_client_dynamite_version", 20290);
    public static final s<Boolean> c0 = s.e(1, "gads:sai:force_through_reflection", Boolean.TRUE);
    public static final s<Boolean> d0 = s.e(1, "gads:sai:gmscore_availability_check_disabled", Boolean.FALSE);
    public static final s<Boolean> e0 = s.e(1, "gads:sai:logging_disabled_for_drx", Boolean.FALSE);
    public static final s<Boolean> f0 = s.e(1, "gads:sai:inject_firebase_proxy", Boolean.FALSE);
    public static final s<Boolean> g0 = s.e(1, "gads:sai:app_measurement_npa_enabled", Boolean.FALSE);
    public static final s<Boolean> h0 = s.e(1, "gads:interstitial:app_must_be_foreground:enabled", Boolean.FALSE);
    public static final s<Boolean> i0 = s.e(1, "gads:interstitial:foreground_report:enabled", Boolean.FALSE);
    public static final s<Boolean> j0 = s.e(1, "gads:webview:error_web_response:enabled", Boolean.FALSE);
    public static final s<Boolean> k0 = s.e(1, "gads:webview:pause_interstitial:enabled", Boolean.TRUE);
    private static final s<Boolean> l0 = s.e(1, "gads:rsku:webviewgone:kill_process:enabled", Boolean.FALSE);
    public static final s<Boolean> m0 = s.e(1, "gads:webviewgone:kill_process:enabled", Boolean.FALSE);
    private static final s<Boolean> n0 = s.e(1, "gads:rsku:webviewgone:new_onshow:enabled", Boolean.TRUE);
    public static final s<Boolean> o0 = s.e(1, "gads:webviewgone:new_onshow:enabled", Boolean.FALSE);
    public static final s<Boolean> p0 = s.e(1, "gads:webview:pause_resume:enabled", Boolean.TRUE);
    public static final s<String> q0 = s.f(1, "gads:webview_cookie_url", "googleads.g.doubleclick.net");
    private static final s<Boolean> r0 = s.e(1, "gads:new_rewarded_ad:enabled", Boolean.TRUE);
    public static final s<Boolean> s0 = s.e(1, "gads:rewarded:adapter_initialization_enabled", Boolean.FALSE);
    private static final s<Long> t0 = s.k(1, "gads:rewarded:adapter_timeout_ms", 20000);
    public static final s<Boolean> u0 = s.e(1, "gads:rewarded:ad_metadata_enabled", Boolean.FALSE);
    public static final s<Boolean> v0 = s.e(1, "gads:rewarded:ssv_custom_data_enabled", Boolean.TRUE);
    public static final s<Long> w0 = s.k(1, "gads:app_activity_tracker:notify_background_listeners_delay_ms", 500);
    public static final s<Long> x0 = s.k(1, "gads:app_activity_tracker:app_session_timeout_ms", TimeUnit.MINUTES.toMillis(5));
    public static final s<Boolean> y0 = s.e(1, "gads:adid_values_in_adrequest:enabled", Boolean.FALSE);
    public static final s<Long> z0 = s.k(1, "gads:adid_values_in_adrequest:timeout", 2000);
    public static final s<Boolean> A0 = s.e(1, "gads:disable_adid_values_in_ms", Boolean.FALSE);
    public static final s<Long> B0 = s.k(1, "gads:ad_overlay:delay_page_close_timeout_ms", 5000);
    public static final s<Boolean> C0 = s.e(1, "gads:custom_close_blocking:enabled", Boolean.FALSE);
    public static final s<Boolean> D0 = s.e(1, "gads:disabling_closable_area:enabled", Boolean.FALSE);
    public static final s<Boolean> E0 = s.e(1, "gads:use_system_ui_for_fullscreen:enabled", Boolean.FALSE);
    public static final s<Boolean> F0 = s.e(1, "gads:ad_overlay:collect_cutout_info:enabled", Boolean.FALSE);
    private static final s<Boolean> G0 = s.e(1, "gads:impression_optimization_enabled", Boolean.FALSE);
    private static final s<String> H0 = s.f(1, "gads:banner_ad_pool:schema", "customTargeting");
    private static final s<Integer> I0 = s.d(1, "gads:banner_ad_pool:max_queues", 3);
    private static final s<Integer> J0 = s.d(1, "gads:banner_ad_pool:max_pools", 3);
    public static final s<Boolean> K0 = s.e(1, "gads:delay_banner_renderer:enabled", Boolean.TRUE);
    private static final s<Boolean> L0 = s.e(1, "gads:interstitial_ad_pool:enabled", Boolean.FALSE);
    private static final s<Boolean> M0 = s.e(1, "gads:interstitial_ad_pool:enabled_for_rewarded", Boolean.FALSE);
    private static final s<String> N0 = s.f(1, "gads:interstitial_ad_pool:schema", "customTargeting");
    private static final s<String> O0 = s.f(1, "gads:interstitial_ad_pool:request_exclusions", "com.google.ads.mediation.admob.AdMobAdapter/_ad");
    private static final s<Integer> P0 = s.d(1, "gads:interstitial_ad_pool:max_pools", 3);
    private static final s<Integer> Q0 = s.d(1, "gads:interstitial_ad_pool:max_pool_depth", 2);
    private static final s<Integer> R0 = s.d(1, "gads:interstitial_ad_pool:time_limit_sec", 1200);
    private static final s<String> S0 = s.f(1, "gads:interstitial_ad_pool:ad_unit_exclusions", "(?!)");
    private static final s<Integer> T0 = s.d(1, "gads:interstitial_ad_pool:top_off_latency_min_millis", 0);
    private static final s<Integer> U0 = s.d(1, "gads:interstitial_ad_pool:top_off_latency_range_millis", 0);
    private static final s<Long> V0 = s.k(1, "gads:interstitial_ad_pool:discard_thresholds", 0);
    private static final s<Long> W0 = s.k(1, "gads:interstitial_ad_pool:miss_thresholds", 0);
    private static final s<Float> X0 = s.c(1, "gads:interstitial_ad_pool:discard_asymptote", 0.0f);
    private static final s<Float> Y0 = s.c(1, "gads:interstitial_ad_pool:miss_asymptote", 0.0f);
    public static final s<String> Z0 = s.f(1, "gads:spherical_video:vertex_shader", "");
    public static final s<String> a1 = s.f(1, "gads:spherical_video:fragment_shader", "");
    public static final s<Boolean> b1 = s.e(1, "gads:include_local_global_rectangles", Boolean.FALSE);
    public static final s<Long> c1 = s.k(1, "gads:position_watcher:throttle_ms", 200);
    public static final s<Long> d1 = s.k(1, "gads:position_watcher:scroll_aware_throttle_ms", 33);
    public static final s<Boolean> e1 = s.e(1, "gads:position_watcher:enable_scroll_aware_ads", Boolean.FALSE);
    public static final s<Boolean> f1 = s.e(1, "gads:position_watcher:send_scroll_data", Boolean.FALSE);
    private static final s<Boolean> g1 = s.e(1, "gads:gen204_signals:enabled", Boolean.FALSE);
    public static final s<Boolean> h1 = s.e(1, "gads:extra_sdk_versions_for_crash_reports:enabled", Boolean.FALSE);
    public static final s<String> i1 = s.f(1, "gads:logged_adapter_version_classes", "");
    public static final s<Long> j1 = s.k(1, "gads:rtb_v1_1:signal_timeout_ms", 1000);
    public static final s<Boolean> k1 = s.e(1, "gads:rtb_signal:enabled", Boolean.TRUE);
    public static final s<Boolean> l1 = s.e(1, "gads:rtb_v1_1:cld:enabled", Boolean.TRUE);
    public static final s<Boolean> m1 = s.e(1, "gads:rtb_v1_1:cld:check_regex:enabled", Boolean.TRUE);
    public static final s<String> n1 = s.f(1, "gads:rtb_logging:regex", "(?!)");
    public static final s<Boolean> o1 = s.e(1, "gads:presentation_error:urls_enabled", Boolean.FALSE);
    public static final s<Boolean> p1 = s.e(1, "gads:rtb_interstitial:use_fullscreen_monitor", Boolean.FALSE);
    public static final s<Boolean> q1 = s.e(1, "gads:v1_1:adapter_initialization:enabled", Boolean.TRUE);
    public static final s<Integer> r1 = s.d(1, "gads:adapter_initialization:min_sdk_version", 15301000);
    public static final s<Long> s1 = s.k(1, "gads:adapter_initialization:timeout", 30);
    public static final s<Long> t1 = s.k(1, "gads:adapter_initialization:cld_timeout", 10);
    public static final s<Boolean> u1 = s.e(1, "gads:initialization_csi:enabled", Boolean.FALSE);
    private static final s<Boolean> v1 = s.e(1, "gads:initialization_csi_control:enabled", Boolean.FALSE);
    public static final s<Boolean> w1 = s.e(1, "gads:msa:experiments:enabled", Boolean.FALSE);
    public static final s<Boolean> x1 = s.e(1, "gads:msa:experiments:ps:enabled", Boolean.FALSE);
    public static final s<Integer> y1 = s.d(1, "gads:gestures:a2:enabled", 0);
    public static final s<Boolean> z1 = s.e(1, "gads:gestures:clearTd:enabled", Boolean.FALSE);
    public static final m1<Boolean> A1 = c2.f2913b;
    public static final s<Boolean> B1 = s.e(1, "gads:gestures:errorlogging:enabled", Boolean.FALSE);
    public static final s<Long> C1 = s.k(1, "gads:gestures:task_timeout", 2000);
    public static final s<Boolean> D1 = s.e(1, "gads:gestures:asig:enabled", Boolean.FALSE);
    public static final s<Boolean> E1 = s.e(1, "gads:gestures:ans:enabled", Boolean.FALSE);
    public static final s<Boolean> F1 = s.e(1, "gads:gestures:tos:enabled", Boolean.FALSE);
    public static final s<Boolean> G1 = s.e(1, "gads:gestures:brt:enabled", Boolean.TRUE);
    public static final s<Boolean> H1 = s.e(1, "gads:gestures:fpi:enabled", Boolean.FALSE);
    public static final s<Boolean> I1 = s.e(1, "gads:signal:app_permissions:disabled", Boolean.FALSE);
    public static final s<Boolean> J1 = s.e(1, "gads:gestures:inthex:enabled", Boolean.FALSE);
    public static final s<Boolean> K1 = s.e(1, "gads:gestures:hpk:enabled", Boolean.TRUE);
    public static final s<String> L1 = s.f(1, "gads:gestures:pk", "");
    public static final s<Boolean> M1 = s.e(1, "gads:gestures:bs:enabled", Boolean.TRUE);
    public static final s<Boolean> N1 = s.e(1, "gads:gestures:check_initialization_thread:enabled", Boolean.FALSE);
    public static final s<Boolean> O1 = s.e(1, "gads:gestures:init_new_thread:enabled", Boolean.TRUE);
    public static final s<Boolean> P1 = s.e(1, "gads:gestures:pds:enabled", Boolean.TRUE);
    private static final s<Integer> Q1 = s.d(1, "gads:gestures:as2percentage", 0);
    public static final s<Boolean> R1 = s.e(1, "gads:gestures:las:enabled", Boolean.FALSE);
    public static final s<Boolean> S1 = s.e(1, "gads:gestures:ns:enabled", Boolean.TRUE);
    public static final s<Boolean> T1 = s.e(1, "gads:gestures:vdd:enabled", Boolean.FALSE);
    public static final s<Boolean> U1 = s.e(1, "gads:native:asset_view_touch_events", Boolean.FALSE);
    public static final s<Boolean> V1 = s.e(1, "gads:native:set_touch_listener_on_asset_views", Boolean.TRUE);
    public static final s<Boolean> W1 = s.e(1, "gads:ais:enabled", Boolean.FALSE);
    public static final s<Boolean> X1 = s.e(1, "gads:stav:enabled", Boolean.FALSE);
    public static final s<Boolean> Y1 = s.e(1, "gads:send_available_disk_space:enabled", Boolean.FALSE);

    static {
        s<String> sVarF = s.f(1, "gads:sdk_core_constants:experiment_id", null);
        qx2.d().c(sVarF);
        Z1 = sVarF;
        a2 = s.f(1, "gads:sdk_core_constants:caps", "");
        b2 = s.e(1, "gads:js_flags:disable_phenotype", Boolean.FALSE);
        c2 = s.f(1, "gads:native:engine_url_with_protocol", "https://googleads.g.doubleclick.net/mads/static/mad/sdk/native/native_ads.html");
        d2 = s.f(1, "gads:native:video_url", "//imasdk.googleapis.com/admob/sdkloader/native_video.html");
        e2 = s.f(1, "gads:native:video_url_with_protocol", "https://imasdk.googleapis.com/admob/sdkloader/native_video.html");
        f2 = s.e(1, "gads:native:get_native_ad_view_signals", Boolean.FALSE);
        g2 = s.d(1, "gads:native_video_load_timeout", 10);
        h2 = s.d(1, "gads:omid:native_webview_load_timeout", 2000);
        i2 = s.e(1, "gads:omid:native_video_ad_user_action_event:enabled", Boolean.FALSE);
        j2 = s.e(1, "gads:enable_native_media_aspect_ratio", Boolean.TRUE);
        k2 = s.e(1, "gads:native:media_content_main_image:enabled", Boolean.TRUE);
        l2 = s.f(1, "gads:ad_choices_content_description", "Ad Choices Icon");
        m2 = s.e(1, "gads:enable_store_active_view_state", Boolean.FALSE);
        n2 = s.e(1, "gads:enable_singleton_broadcast_receiver", Boolean.FALSE);
        o2 = s.e(1, "gads:native:media_view_match_parent:enabled", Boolean.FALSE);
        p2 = s.e(1, "gads:native:count_impression_for_assets", Boolean.FALSE);
        q2 = s.e(1, "gads:instream_ad:enabled", Boolean.TRUE);
        r2 = s.e(1, "gads:fluid_ad:use_wrap_content_height", Boolean.FALSE);
        s2 = s.e(1, "gads:auto_location_for_coarse_permission", Boolean.FALSE);
        t2 = s.j(1, "gads:auto_location_for_coarse_permission:experiment_id");
        u2 = s.k(1, "gads:auto_location_timeout", 2000L);
        v2 = s.j(1, "gads:auto_location_timeout:experiment_id");
        w2 = s.k(1, "gads:auto_location_interval", -1L);
        x2 = s.j(1, "gads:auto_location_interval:experiment_id");
        y2 = s.e(1, "gads:rtb_v1_1:fetch_app_settings_using_cld:enabled", Boolean.TRUE);
        z2 = s.e(1, "gads:get_request_signals_cld:enabled", Boolean.FALSE);
        A2 = s.e(1, "gads:rtb_v1_1:use_manifest_appid_cld:enabled", Boolean.TRUE);
        B2 = s.k(1, "gads:fetch_app_settings_using_cld:refresh_interval_ms", 7200000L);
        C2 = s.k(1, "gads:parental_controls:timeout", 2000L);
        D2 = s.d(1, "gads:cache:ad_request_timeout_millis", m.f.f720c);
        E2 = s.d(1, "gads:cache:max_concurrent_downloads", 10);
        F2 = s.k(1, "gads:cache:javascript_timeout_millis", 5000L);
        G2 = s.e(1, "gads:cache:bind_on_foreground", Boolean.FALSE);
        H2 = s.e(1, "gads:cache:bind_on_init", Boolean.FALSE);
        I2 = s.e(1, "gads:cache:bind_on_request", Boolean.FALSE);
        J2 = s.k(1, "gads:cache:bind_on_request_keep_alive", TimeUnit.SECONDS.toMillis(30L));
        K2 = s.e(1, "gads:cache:use_cache_data_source", Boolean.FALSE);
        L2 = s.e(1, "gads:cache:connection_per_read", Boolean.FALSE);
        M2 = s.k(1, "gads:cache:connection_timeout", 5000L);
        N2 = s.k(1, "gads:cache:read_only_connection_timeout", 5000L);
        O2 = s.e(1, "gads:http_assets_cache:enabled", Boolean.FALSE);
        P2 = s.f(1, "gads:http_assets_cache:regex", "(?i)https:\\/\\/(tpc\\.googlesyndication\\.com\\/(.*)|lh\\d+\\.googleusercontent\\.com\\/(.*))");
        Q2 = s.d(1, "gads:http_assets_cache:time_out", 100);
        R2 = s.e(1, "gads:chrome_custom_tabs_browser:enabled", Boolean.FALSE);
        S2 = s.e(1, "gads:chrome_custom_tabs:disabled", Boolean.FALSE);
        T2 = s.k(1, "gads:debug_hold_gesture:time_millis", 2000L);
        U2 = s.f(1, "gads:drx_debug:debug_device_linking_url", "https://www.google.com/dfp/linkDevice");
        V2 = s.f(1, "gads:drx_debug:in_app_preview_status_url", "https://www.google.com/dfp/inAppPreview");
        W2 = s.f(1, "gads:drx_debug:debug_signal_status_url", "https://www.google.com/dfp/debugSignals");
        X2 = s.f(1, "gads:drx_debug:send_debug_data_url", "https://www.google.com/dfp/sendDebugData");
        Y2 = s.d(1, "gads:drx_debug:timeout_ms", 5000);
        Z2 = s.d(1, "gad:pixel_dp_comparision_multiplier", 1);
        a3 = s.e(1, "gad:interstitial_for_multi_window", Boolean.FALSE);
        b3 = s.e(1, "gad:interstitial_ad_stay_active_in_multi_window", Boolean.FALSE);
        c3 = s.e(1, "gad:interstitial_multi_window_method", Boolean.FALSE);
        d3 = s.d(1, "gad:interstitial:close_button_padding_dip", 0);
        e3 = s.e(1, "gads:clearcut_logging:enabled", Boolean.FALSE);
        f3 = s.e(1, "gads:clearcut_logging:write_to_file", Boolean.FALSE);
        g3 = s.e(1, "gad:publisher_testing:force_local_request:enabled", Boolean.TRUE);
        h3 = s.f(1, "gad:publisher_testing:force_local_request:enabled_list", "");
        i3 = s.f(1, "gad:publisher_testing:force_local_request:disabled_list", "");
        j3 = s.d(1, "gad:http_redirect_max_count:times", 8);
        k3 = s.e(1, "gads:omid:enabled", Boolean.TRUE);
        l3 = s.d(1, "gads:omid:destroy_webview_delay", 1000);
        m3 = s.e(1, "gads:omid_1_3_activate:enabled", Boolean.FALSE);
        n3 = s.e(1, "gads:omid_1_3_create_html_session:enabled", Boolean.FALSE);
        o3 = s.e(1, "gads:omid_1_3_create_js_session:enabled", Boolean.FALSE);
        p3 = s.e(1, "gads:nonagon:banner:enabled", Boolean.TRUE);
        q3 = s.f(1, "gads:nonagon:banner:ad_unit_exclusions", "(?!)");
        r3 = s.e(1, "gads:nonagon:app_open:enabled", Boolean.TRUE);
        s3 = s.d(1, "gads:app_open_beta:min_version", 999999999);
        t3 = s.d(1, "gads:app_open_ad_open_beta_api:min_version", 202490999);
        u3 = s.f(1, "gads:nonagon:app_open:ad_unit_exclusions", "(?!)");
        v3 = s.e(1, "gads:nonagon:interstitial:enabled", Boolean.TRUE);
        w3 = s.f(1, "gads:nonagon:interstitial:ad_unit_exclusions", "(?!)");
        x3 = s.e(1, "gads:nonagon:rewardedvideo:enabled", Boolean.TRUE);
        y3 = s.e(1, "gads:nonagon:mobile_ads_setting_manager:enabled", Boolean.TRUE);
        z3 = s.f(1, "gads:nonagon:rewardedvideo:ad_unit_exclusions", "(?!)");
        A3 = s.e(1, "gads:nonagon:nativead:enabled", Boolean.TRUE);
        B3 = s.f(1, "gads:nonagon:nativead:app_name", "(?!)");
        C3 = s.e(1, "gads:nonagon:banner:check_dp_size", Boolean.TRUE);
        D3 = s.e(1, "gads:nonagon:rewarded:load_multiple_ads", Boolean.TRUE);
        E3 = s.e(1, "gads:nonagon:return_last_error_code", Boolean.FALSE);
        F3 = s.e(1, "gads:nonagon:return_no_fill_error_code", Boolean.FALSE);
        G3 = s.e(1, "gads:nonagon:continue_on_no_fill", Boolean.FALSE);
        H3 = s.e(1, "gads:nonagon:open_not_loaded_interstitial", Boolean.TRUE);
        I3 = s.e(1, "gads:nonagon:separate_timeout:enabled", Boolean.TRUE);
        J3 = s.d(1, "gads:nonagon:request_timeout:seconds", 60);
        K3 = s.e(1, "gads:nonagon:banner_recursive_renderer", Boolean.FALSE);
        L3 = s.e(1, "gads:nonagon:app_stats_lock:enabled", Boolean.FALSE);
        M3 = s.e(1, "gads:nonagon:app_stats_main_thread:enabled", Boolean.FALSE);
        N3 = s.e(1, "gads:uri_query_to_map_bg_thread:enabled", Boolean.FALSE);
        O3 = s.e(1, "gads:nonagon:active_view_gmsg_background_thread:enabled", Boolean.TRUE);
        P3 = s.e(1, "gads:active_view_gmsg_separate_pool:enabled", Boolean.TRUE);
        Q3 = s.e(1, "gads:nonagon:service:enabled", Boolean.TRUE);
        R3 = s.e(1, "gads:nonagon:dpl_cancel_destroy_webview:enabled", Boolean.FALSE);
        S3 = s.e(1, "gads:signals:ad_id_info:enabled", Boolean.FALSE);
        T3 = s.e(1, "gads:signals:app_index:enabled", Boolean.FALSE);
        U3 = s.e(1, "gads:signals:attestation_token:enabled", Boolean.FALSE);
        V3 = s.e(1, "gads:signals:cache:enabled", Boolean.FALSE);
        W3 = s.e(1, "gads:signals:doritos:enabled", Boolean.FALSE);
        X3 = s.e(1, "gads:signals:doritos:v1:enabled", Boolean.FALSE);
        Y3 = s.e(1, "gads:signals:doritos:v2:immediate:enabled", Boolean.FALSE);
        Z3 = s.e(1, "gads:signals:location:enabled", Boolean.FALSE);
        a4 = s.e(1, "gads:signals:network_prediction:enabled", Boolean.FALSE);
        b4 = s.e(1, "gads:signals:parental_control:enabled", Boolean.FALSE);
        c4 = s.e(1, "gads:signals:video_decoder:enabled", Boolean.FALSE);
        d4 = s.e(1, "gads:signals:app_version_name:enabled", Boolean.FALSE);
        e4 = s.e(1, "gads:attestation_token:enabled", Boolean.FALSE);
        f4 = s.k(1, "gads:mobius_linking:sdk_side_cooldown_time_threshold:ms", 3600000L);
        g4 = s.d(1, "gads:adoverlay:b68684796:targeting_sdk:lower_bound", 27);
        h4 = s.d(1, "gads:adoverlay:b68684796:targeting_sdk:upper_bound", 26);
        i4 = s.d(1, "gads:adoverlay:b68684796:sdk_int:lower_bound", 27);
        j4 = s.d(1, "gads:adoverlay:b68684796:sdk_int:upper_bound", 26);
        k4 = d2.f3059a;
        l4 = s.e(1, "gads:consent:shared_preference_reading:enabled", Boolean.TRUE);
        m4 = s.e(1, "gads:consent:iab_consent_info:enabled", Boolean.TRUE);
        n4 = s.e(1, "gads:fc_consent:shared_preference_reading:enabled", Boolean.TRUE);
        o4 = s.f(1, "gads:sp:json_string", "");
        p4 = s.e(1, "gads:nativeads:image:sample:enabled", Boolean.TRUE);
        q4 = s.d(1, "gads:nativeads:image:sample:pixels", 1048576);
        r4 = s.e(1, "gads:nativeads:pub_image_scale_type:enabled", Boolean.TRUE);
        s4 = s.e(1, "gads:offline_signaling:enabled", Boolean.FALSE);
        t4 = s.d(1, "gads:offline_signaling:log_maximum", 100);
        u4 = s.e(1, "gads:nativeads:template_signal:enabled", Boolean.TRUE);
        v4 = s.e(1, "gads:nativeads:media_content_aspect_ratio:enabled", Boolean.TRUE);
        w4 = s.e(1, "gads:nativeads:media_content_metadata:enabled", Boolean.TRUE);
        x4 = s.e(1, "gads:ar_ads:enabled", Boolean.FALSE);
        y4 = s.e(1, "gads:precache_pool:verbose_logging", Boolean.FALSE);
        z4 = s.d(1, "gads:rewarded_precache_pool:count", 0);
        A4 = s.d(1, "gads:interstitial_precache_pool:count", 0);
        B4 = s.f(1, "gads:rewarded_precache_pool:discard_strategy", "lru");
        C4 = s.f(1, "gads:interstitial_precache_pool:discard_strategy", "lru");
        D4 = s.f(1, "gads:rewarded_precache_pool:cache_start_trigger", "onAdClosed");
        E4 = s.f(1, "gads:interstitial_precache_pool:cache_start_trigger", "onAdClosed");
        F4 = s.d(1, "gads:rewarded_precache_pool:size", 1);
        G4 = s.d(1, "gads:interstitial_precache_pool:size", 1);
        H4 = s.d(1, "gads:rewarded_precache_pool:ad_time_limit", 1200);
        I4 = s.d(1, "gads:interstitial_precache_pool:ad_time_limit", 1200);
        J4 = s.f(1, "gads:rewarded_precache_pool:schema", "customTargeting,npa,tagForChildDirectedTreatment,tagForUnderAgeOfConsent,maxAdContentRating");
        K4 = s.f(1, "gads:interstitial_precache_pool:schema", "customTargeting,npa,tagForChildDirectedTreatment,tagForUnderAgeOfConsent,maxAdContentRating");
        L4 = s.f(1, "gads:app_open_precache_pool:schema", "orientation,npa,tagForChildDirectedTreatment,tagForUnderAgeOfConsent,maxAdContentRating");
        M4 = s.f(1, "gads:app_open_precache_pool:discard_strategy", "oldest");
        N4 = s.d(1, "gads:app_open_precache_pool:count", 0);
        O4 = s.f(1, "gads:app_open_precache_pool:cache_start_trigger", "onAdClosed");
        P4 = s.d(1, "gads:app_open_precache_pool:size", 1);
        Q4 = s.d(1, "gads:app_open_precache_pool:ad_time_limit", 14400);
        R4 = s.e(1, "gads:memory_leak:b129558083", Boolean.FALSE);
        S4 = s.e(1, "gads:unhandled_event_reporting:enabled", Boolean.FALSE);
        T4 = s.e(1, "gads:response_info:enabled", Boolean.TRUE);
        U4 = s.e(1, "gads:csi:interstitial_failed_to_show:enabled", Boolean.FALSE);
        V4 = s.e(1, "gads:csi:mediation_failure:enabled", Boolean.FALSE);
        W4 = s.f(1, "gads:csi:error_parsing:regex", "^(\\d+)");
        X4 = s.e(1, "gads:signal_collection_without_rendering:enabled", Boolean.TRUE);
        Y4 = s.d(1, "gads:native_ads_signal:timeout", 1000);
        Z4 = s.d(1, "gads:signal_v2:min_version", 19677000);
        a5 = s.e(2, "DISABLE_CRASH_REPORTING", Boolean.FALSE);
        b5 = s.e(1, "gads:paid_event_listener:enabled", Boolean.FALSE);
        c5 = s.e(1, "gads:interscroller_ad:enabled", Boolean.TRUE);
        d5 = s.e(1, "gads:interscroller_ad:refresh:enabled", Boolean.FALSE);
        e5 = s.e(1, "gads:is_in_scroll_view_new_api:enabled", Boolean.TRUE);
        f5 = s.e(1, "gads:native_ad_policy_validator:enabled", Boolean.TRUE);
        g5 = s.d(1, "gads:policy_validator_layoutparam:flags", 808);
        h5 = s.e(2, "NATIVE_AD_DEBUGGER_ENABLED", Boolean.FALSE);
        i5 = s.d(1, "gads:policy_validator_overlay_width:dp", 350);
        j5 = s.d(1, "gads:policy_validator_overlay_height:dp", 140);
        k5 = s.e(1, "gads:use_wide_viewport:enabled", Boolean.FALSE);
        l5 = s.e(1, "gads:load_with_overview_mode:enabled", Boolean.FALSE);
        m5 = s.e(1, "gads:wire_banner_listener_after_request:enabled", Boolean.FALSE);
        n5 = s.e(1, "gads:wire_rewarded_listener_after_request:enabled", Boolean.FALSE);
        o5 = s.e(1, "gads:wire_app_open_listener_after_request:enabled", Boolean.FALSE);
        p5 = s.e(1, "gads:wire_interstitial_listener_after_request:enabled", Boolean.FALSE);
        q5 = s.e(1, "gads:wire_ad_loader_listener_after_request:enabled", Boolean.FALSE);
        r5 = s.e(1, "gads:server_transaction_source:enabled", Boolean.FALSE);
        s5 = s.f(1, "gads:server_transaction_source:list", "Network");
        t5 = s.e(1, "gads:can_open_app_and_open_app_action:enabled", Boolean.FALSE);
        u5 = s.e(1, "gads:open_gmsg:set_uri_data_and_type:enabled", Boolean.FALSE);
        v5 = s.d(1, "gads:ad_error_api:min_version", 999999999);
        w5 = s.e(1, "gads:forward_bow_error_string:enabled", Boolean.FALSE);
        x5 = s.e(1, "gads:mediation_status_reporting:enabled", Boolean.TRUE);
        y5 = s.d(1, "gads:mediation_no_fill_error:min_version", 999999999);
        z5 = s.e(1, "gads:default_network_type_fine_to_unknown:enabled", Boolean.TRUE);
    }

    public static void a(final Context context) {
        ar.b(new cv1(context) { // from class: com.google.android.gms.internal.ads.h0

            /* renamed from: a, reason: collision with root package name */
            private final Context f3600a;

            {
                this.f3600a = context;
            }

            @Override // com.google.android.gms.internal.ads.cv1
            public final Object get() {
                return e0.c(this.f3600a);
            }
        });
    }

    /* JADX WARN: Type inference failed for: r0v1, types: [com.google.android.gms.internal.ads.r2, com.google.android.gms.internal.ads.x] */
    public static void b(Context context, int r22, JSONObject jSONObject) {
        qx2.c();
        SharedPreferences.Editor editorEdit = context.getSharedPreferences("google_ads_flags", 0).edit();
        r1.a(new x(qx2.d(), editorEdit, jSONObject));
        qx2.d().a(editorEdit, 1, jSONObject);
        qx2.c();
        editorEdit.commit();
    }

    static final /* synthetic */ Object c(Context context) {
        qx2.e().a(context);
        return null;
    }

    public static List<String> d() {
        return qx2.d().e();
    }

    public static List<String> e() {
        return qx2.d().f();
    }
}
