package com.google.android.gms.internal.ads;

import android.content.Context;
import android.content.pm.ApplicationInfo;
import android.content.pm.PackageInfo;
import android.os.Bundle;
import com.google.android.gms.internal.ads.cv2;
import java.util.Map;
import java.util.Set;

/* loaded from: classes.dex */
final class g10 extends q81 {
    private ze2<sw0> A;
    private ze2<dy1<p91>> A0;
    private ze2<o91> B;
    private final /* synthetic */ e00 B0;
    private ze2<Context> C;
    private ze2<ApplicationInfo> D;
    private ze2<PackageInfo> E;
    private ze2<dy1<String>> F;
    private ze2<qo> G;
    private ze2<ho> H;
    private ze2<an1> I;
    private ze2<un> J;
    private ze2<s80> K;
    private ze2<String> L;
    private ze2<ao1> M;
    private ze2<za1> N;
    private ze2<ea1> O;
    private ze2<y91> P;
    private ze2<Set<String>> Q;
    private ze2<od1> R;
    private ze2<ma1> S;
    private ze2<oc1> T;
    private ze2 U;
    private ze2<Bundle> V;
    private ze2<wd1> W;
    private ze2<ic1> X;
    private ze2<rd1> Y;
    private ze2<ce1> Z;

    /* renamed from: a, reason: collision with root package name */
    private ze2<String> f3485a;
    private ze2<rk1> a0;

    /* renamed from: b, reason: collision with root package name */
    private ze2<eo1> f3486b;
    private ze2<ve1> b0;

    /* renamed from: c, reason: collision with root package name */
    private ze2<Context> f3487c;
    private ze2<qa1> c0;
    private ze2<String> d;
    private ze2<kb1> d0;
    private ze2<cv2.a.EnumC0172a> e;
    private ze2<dy1<String>> e0;
    private ze2<String> f;
    private ze2<aa1> f0;
    private ze2<tu2> g;
    private ze2<qe1> g0;
    private ze2<tt0> h;
    private ze2<qf1> h0;
    private ze2<tt0> i;
    private ze2<wc1> i0;
    private ze2<Map<zq1, tt0>> j;
    private ze2<me1> j0;
    private ze2<rt0> k;
    private ze2<sc1> k0;
    private ze2<Set<ch0<ir1>>> l;
    private ze2<ad1> l0;
    private ze2<fu0> m;
    private ze2<va1> m0;
    private ze2 n;
    private ze2<ec1> n0;
    private ze2<lu0> o;
    private ze2<String> o0;
    private ze2<ch0<ir1>> p;
    private ze2<x61> p0;
    private ze2<gv0> q;
    private ze2<ge1> q0;
    private ze2<Set<ch0<ir1>>> r;
    private ze2<db1> r0;
    private ze2<vz0> s;
    private ze2<we1> s0;
    private ze2<wz0> t;
    private ze2<sj1> t0;
    private ze2<ch0<ir1>> u;
    private ze2<pb1> u0;
    private ze2<Set<ch0<ir1>>> v;
    private ze2<ae1> v0;
    private ze2 w;
    private ze2<vb1> w0;
    private ze2<cr1> x;
    private ze2<Set<ff1<? extends cf1<Bundle>>>> x0;
    private ze2<nx0> y;
    private ze2<ef1<Bundle>> y0;
    private ze2<my0> z;
    private ze2<fa0> z0;

    private g10(e00 e00Var, g91 g91Var, i80 i80Var, wu0 wu0Var, ia0 ia0Var, go1 go1Var, rk1 rk1Var, sj1 sj1Var) {
        this.B0 = e00Var;
        this.f3485a = ma0.a(ia0Var);
        ze2<eo1> ze2VarA = me2.a(io1.a(go1Var, this.B0.J, this.f3485a));
        this.f3486b = ze2VarA;
        lo1 lo1VarB = lo1.b(go1Var, ze2VarA);
        this.f3487c = lo1VarB;
        this.d = nw0.a(lo1VarB);
        this.e = me2.a(new k91(g91Var));
        this.f = me2.a(qw0.a());
        this.g = me2.a(ns0.a(this.B0.k, this.d, this.B0.l, this.e, this.f));
        this.h = me2.a(ws0.a());
        this.i = me2.a(ys0.a());
        se2 se2VarB = ((ue2) ((ue2) se2.b(2).a(zq1.SIGNALS, this.h)).a(zq1.RENDERER, this.i)).b();
        this.j = se2VarB;
        this.k = st0.a(this.g, se2VarB);
        this.l = me2.a(at0.a(bq1.a(), this.k));
        this.m = me2.a(eu0.a(this.B0.s));
        ve2 ve2VarC = ve2.a(1, 0).a(du0.a()).c();
        this.n = ve2VarC;
        ze2<lu0> ze2VarA2 = me2.a(ou0.a(this.m, ve2VarC, this.B0.h));
        this.o = ze2VarA2;
        this.p = me2.a(au0.a(ze2VarA2, bq1.a()));
        ze2<gv0> ze2VarA3 = me2.a(fv0.a(this.B0.K, this.B0.y));
        this.q = ze2VarA3;
        this.r = dv0.a(wu0Var, ze2VarA3, bq1.a());
        ze2<vz0> ze2VarA4 = me2.a(uz0.a());
        this.s = ze2VarA4;
        zz0 zz0VarA = zz0.a(ze2VarA4);
        this.t = zz0VarA;
        this.u = me2.a(jz0.a(zz0VarA, bq1.a()));
        ve2 ve2VarC2 = ve2.a(2, 2).b(this.l).a(this.p).b(this.r).a(this.u).c();
        this.v = ve2VarC2;
        this.w = kr1.a(ve2VarC2);
        this.x = me2.a(hr1.a(bq1.a(), this.B0.f, this.w));
        this.y = new px0(this.B0.k);
        this.z = dz0.a(this.B0.k, this.B0.d, c00.f2904a, this.B0.R, this.B0.S, this.B0.T);
        this.A = new uw0(this.B0.f, bq1.a(), this.y, this.z);
        this.B = new q91(bq1.a(), this.A);
        ze2<Context> ze2VarA5 = me2.a(la0.a(ia0Var, this.f3487c));
        this.C = ze2VarA5;
        jw0 jw0VarA = jw0.a(ze2VarA5);
        this.D = jw0VarA;
        this.E = me2.a(kw0.a(this.C, jw0VarA));
        this.F = me2.a(hw0.a(this.x, this.C));
        this.G = jo1.b(go1Var, this.f3486b);
        this.H = ko1.a(go1Var, this.f3486b);
        this.I = pa0.a(ia0Var);
        this.J = me2.a(o80.a(this.B0.h, this.H, this.I));
        ze2<s80> ze2VarA6 = me2.a(q80.a(this.B0.h, this.J));
        this.K = ze2VarA6;
        this.L = na0.b(ia0Var, ze2VarA6);
        this.M = me2.a(do1.a(this.f3487c, this.H));
        this.N = bb1.a(this.L, this.B0.p, this.K, this.M, this.I);
        this.O = ga1.a(this.B0.N, this.I, this.f3487c, this.B0.G);
        this.P = x91.a(this.I);
        this.Q = me2.a(new m91(g91Var));
        this.R = qd1.a(this.B0.L, this.f3487c, this.Q);
        this.S = oa1.a(this.L, this.B0.L, this.B0.j);
        this.T = qc1.a(this.C, bq1.a());
        this.U = la1.a(this.Q);
        this.V = oa0.a(ia0Var);
        this.W = yd1.a(bq1.a(), this.V);
        this.X = mc1.b(this.f3487c, bq1.a());
        this.Y = ud1.b(this.D, this.E);
        this.Z = ee1.a(this.B0.k, this.f3485a);
        pe2 pe2VarB = oe2.b(rk1Var);
        this.a0 = pe2VarB;
        this.b0 = xe1.a(pe2VarB);
        this.c0 = sa1.a(bq1.a(), this.I, this.B0.l);
        this.d0 = mb1.a(bq1.a(), this.f3487c);
        ze2<dy1<String>> ze2VarA7 = me2.a(ew0.a(this.B0.z, this.f3487c, bq1.a()));
        this.e0 = ze2VarA7;
        this.f0 = ba1.a(ze2VarA7, bq1.a());
        this.g0 = se1.a(bq1.a(), this.f3487c, this.B0.l);
        this.h0 = sf1.a(bq1.a(), this.f3487c);
        this.i0 = yc1.a(bq1.a());
        this.j0 = oe1.a(this.B0.v, bq1.a(), this.f3487c);
        this.k0 = uc1.a(bq1.a());
        this.l0 = cd1.a(bq1.a(), this.B0.Q);
        this.m0 = wa1.b(bq1.a(), this.B0.G);
        this.n0 = jc1.a(this.B0.I, this.B0.f, this.G, this.D, this.I);
        this.o0 = me2.a(new j91(g91Var));
        this.p0 = me2.a(w61.a(this.B0.j));
        this.q0 = ke1.a(bq1.a(), this.B0.f, this.o0, this.B0.n, this.C, this.I, this.p0);
        this.r0 = ib1.a(this.f3487c, this.B0.f, bq1.a());
        this.s0 = df1.b(bq1.a(), this.f3487c);
        pe2 pe2VarB2 = oe2.b(sj1Var);
        this.t0 = pe2VarB2;
        this.u0 = rb1.a(pe2VarB2);
        this.v0 = zd1.a(this.f);
        this.w0 = xb1.a(bq1.a(), this.B0.w, this.I, this.o0);
        this.x0 = ve2.a(31, 0).a(this.N).a(this.O).a(this.P).a(this.R).a(this.S).a(this.T).a(this.U).a(this.W).a(this.X).a(this.Y).a(this.Z).a(this.b0).a(this.c0).a(this.d0).a(this.f0).a(this.g0).a(this.B0.N).a(this.h0).a(this.B0.P).a(this.i0).a(this.j0).a(this.k0).a(this.l0).a(this.m0).a(this.n0).a(this.q0).a(this.r0).a(this.s0).a(this.u0).a(this.v0).a(this.w0).c();
        this.y0 = kf1.b(bq1.a(), this.x0);
        ha0 ha0VarA = ha0.a(this.x, this.B0.l, this.D, this.d, iw0.a(), this.E, this.F, this.G, this.f, this.y0);
        this.z0 = ha0VarA;
        this.A0 = me2.a(new l91(this.x, this.B, ha0VarA));
    }

    @Override // com.google.android.gms.internal.ads.q81
    public final dy1<p91> a() {
        return this.A0.get();
    }
}
